-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 15:14:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BuscaTec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BuscaTec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BuscaTec` DEFAULT CHARACTER SET utf8 ;
USE `BuscaTec` ;

-- -----------------------------------------------------
-- Table `BuscaTec`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuscaTec`.`Usuario` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(32) NULL,
  `Senha` VARCHAR(255) NULL,
  `CPF` VARCHAR(32) NULL,
  `Email` VARCHAR(45) NULL,
  `Fone` VARCHAR(45) NULL,
  `Photo` VARCHAR(45) NOT NULL,
  `Type` BLOB NULL,
  PRIMARY KEY (`ID_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuscaTec`.`Perfil_Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuscaTec`.`Perfil_Profissional` (
  `ID_Perfil_Profissional` INT NOT NULL,
  `FK_ID_Usuario` INT NULL,
  `Historico_Profissional` VARCHAR(45) NULL,
  `Certificado` VARCHAR(45) NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`ID_Perfil_Profissional`),
  INDEX `fk_Perfil_Profissional_Usuario_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Profissional_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `BuscaTec`.`Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuscaTec`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuscaTec`.`Servico` (
  `ID_Servico` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(600) NULL,
  `Valor` REAL NULL,
  `Status` TINYINT NULL,
  `Usuario_id` INT NOT NULL,
  `Perfil_Profissional_ID_Perfil_Profissional` INT NOT NULL,
  PRIMARY KEY (`ID_Servico`),
  INDEX `fk_Servico_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `fk_Servico_Perfil_Profissional1_idx` (`Perfil_Profissional_ID_Perfil_Profissional` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `BuscaTec`.`Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Perfil_Profissional1`
    FOREIGN KEY (`Perfil_Profissional_ID_Perfil_Profissional`)
    REFERENCES `BuscaTec`.`Perfil_Profissional` (`ID_Perfil_Profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuscaTec`.`Visita_Tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuscaTec`.`Visita_Tecnica` (
  `ID_Visita` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Time` TIME NULL,
  `Usuario_id` INT NOT NULL,
  `Perfil_Profissional_ID_Perfil_Profissional` INT NOT NULL,
  `Servico_ID_Servico` INT NOT NULL,
  PRIMARY KEY (`ID_Visita`),
  INDEX `fk_Visita_Tecnica_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  INDEX `fk_Visita_Tecnica_Perfil_Profissional1_idx` (`Perfil_Profissional_ID_Perfil_Profissional` ASC) VISIBLE,
  INDEX `fk_Visita_Tecnica_Servico1_idx` (`Servico_ID_Servico` ASC) VISIBLE,
  CONSTRAINT `fk_Visita_Tecnica_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `BuscaTec`.`Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Tecnica_Perfil_Profissional1`
    FOREIGN KEY (`Perfil_Profissional_ID_Perfil_Profissional`)
    REFERENCES `BuscaTec`.`Perfil_Profissional` (`ID_Perfil_Profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Tecnica_Servico1`
    FOREIGN KEY (`Servico_ID_Servico`)
    REFERENCES `BuscaTec`.`Servico` (`ID_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
